AUREBESH = {
    'a': 'Aurek',
    'b': 'Besh',
    'c': 'Cresh',
    'd': 'Dorn',
    'e': 'Esk',
    'f': 'Forn',
    'g': 'Grek',
    'h': 'Herf',
    'i': 'Isk',
    'j': 'Jenth',
    'k': 'Krill',
    'l': 'Leth',
    'm': 'Mern',
    'n': 'Nern',
    'o': 'Osk',
    'p': 'Peth',
    'q': 'Qek',
    'r': 'Resh',
    's': 'Senth',
    't': 'Trill',
    'u': 'Usk',
    'v': 'Vev',
    'w': 'Wesk',
    'x': 'Xesh',
    'y': 'Yirt',
    'z': 'Zerek',
}

def traductor(text: str):
